encoding: 'utf-8'
language: 'en-us'

# Site Settings
title: 'Unicode For You'
author:
  name: 'Brandon Brown'
  email: 'brandon@brandonb.io'
description: Start typing to search for a character,<br /> then click one to have it copied instantly to your clipboard!
meta_description: A useful unicode emoji map. Click on a character to have it copied to your clipboard!
# meta_image: ''

# Favicons
favicon:
  ico: /favicon.ico
  png: /logo-144.png
  theme_color: '#FFFFFF'

# Routes
baseurl: '' # Use if your site is in a subdirectory, e.g. /blog/
root: /
permalink: /:title

assets_scripts: /assets/scripts
assets_styles: /assets/styles

# Build-stuff
keep_files: [
  'assets']

# 3rd-party
social:
  github: brandonb927
  twitter: brandonb927

google_analytics:
  id: UA-83002300-1
  domain: unicodeforyou.surge.sh
