# Routes
url: "http://localhost:8888"

# Disable some things for development
google_analytics:
  id: false
  domain: false

# Build settings
exclude: [
  '.ruby-version',
  '.editorconfig',
  '.bowerrc',
  'README.md',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.babel.js',
  'package.json',
  'gulp_tasks',
  'node_modules',
  'build_prod']
