encoding: 'utf-8'
language: 'en-us'

# Site Settings
title: 'Unicode For You'
author:
  name: 'Brandon Brown'
  email: 'brandon@brandonb.io'
description: ''
meta_description: >
  A useful unicode/emoji character map. Click on a character to
  have it copied to your clipboard, or use your arrow keys and hit enter to copy.

# Favicons
favicon:
  ico: /favicon.ico
  png: /logo-144.png
  theme_color: '#FFFFFF'

social:
  github: brandonb927
  twitter: brandonb927

google_analytics:
  id: UA-83002300-1
  domain: unicodeforyou.surge.sh

# Routes
baseurl: '' # Use if your site is in a subdirectory, e.g. /blog/
root: /
permalink: /:title

assets_scripts: /assets/scripts
assets_styles: /assets/styles

# Build-stuff
destination: dist
source: src

keep_files: [
  'assets',
  'unicode.json']

exclude: [
  'assets',
  'node_modules']
